version: '3.1'
services:

  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
    - ./mongodb/data:/data/db
    restart: always
    environment:
    - MONGODB_USERNAME=kgrachev
    - MONGODB_PASSWORD=po04uy76
    - MONGODB_DATABASE=admin

  api:
    build: ./api
    ports:
    - 3000:3000
    restart: always